[project]
name = "tb-inference"
version = "0.1.0"
description = "Tuberculosis detection inference module"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.0",
    "pydicom>=3.0.1",
    "pillow>=10.0.0",
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
    "python-multipart>=0.0.21",
    "timm>=0.9.0", 
    "opencv-python",
    "matplotlib>=3.8.0"
]


